# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Getignore < Formula
  desc "Fetch gitignore files right from your terminal"
  homepage "https://github.com/haroldadmin/getignore"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/haroldadmin/getignore/releases/download/0.2.1/getignore_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "0d51c6323be942a81e2d513138974f1940d89414076a2cb7ff3688572c430b23"

      def install
        bin.install "getignore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/haroldadmin/getignore/releases/download/0.2.1/getignore_0.2.1_Darwin_arm64.tar.gz"
      sha256 "e87cb42cd828f0a311951614e1229d862523246973c87cf61c7f1b0e62dd714b"

      def install
        bin.install "getignore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/haroldadmin/getignore/releases/download/0.2.1/getignore_0.2.1_Linux_x86_64.tar.gz"
      sha256 "35f5e3bb3d830dddd9bacb756c068aa2cdeae5043f2bac3fff63af687be0a35a"

      def install
        bin.install "getignore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haroldadmin/getignore/releases/download/0.2.1/getignore_0.2.1_Linux_arm64.tar.gz"
      sha256 "18ebbb7abe7d8518cad32a3d9a9ea594588ae7f5f38ca8ad73e25af63f98d831"

      def install
        bin.install "getignore"
      end
    end
  end
end
